modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="jimsmineshaft"
version="1.0.0"
displayName="jimsmineshaft"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "jimsmineshaft.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.jimsmineshaft]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.jimsmineshaft]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration